name: Smart Daily Commits

on:
  schedule:
    # Runs every 6 hours — 12 AM, 6 AM, 12 PM, 6 PM UTC
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config user.name "O-BERNARDOFOEGBU"
          git config user.email "obinnaofoegbu71@gmail.com"

      - name: Generate smart commits
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          touch daily-log.md
          DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          # Choose 2–4 commits per run
          COMMITS=$(( (RANDOM % 3) + 2 ))

          echo "Planned $COMMITS commits for this run."

          MESSAGES=(
            "Keep building — progress compounds."
            "Code. Commit. Grow."
            "Every small step leads somewhere great."
            "Innovation loves consistency."
            "Legacy in the making."
            "Discipline today, dominance tomorrow."
            "You're coding your future."
            "Bernard, the world remembers the consistent ones."
            "Just improving things quietly."
            "Writing code, writing history."
          )

          for ((i=1; i<=COMMITS; i++)); do
            MSG=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}
            TIME=$(date -u +"%H:%M:%S UTC")
            echo "- **$DATE $TIME** — $MSG (commit $i/$COMMITS)" >> daily-log.md
            git add daily-log.md
            git commit -m "Auto-log: $DATE $TIME — $MSG (commit $i/$COMMITS)" || true
          done

          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
